import type { MaestroCommand, TapOnSelector } from '@maestro-recorder/shared';

export class YamlGenerator {
  generate(appId: string, commands: MaestroCommand[]): string {
    const processed = this.postProcess(commands);
    const lines: string[] = [];
    const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19);

    lines.push(`# Generated by MaestroRecorder`);
    lines.push(`# Recorded: ${timestamp}`);
    lines.push(`appId: ${appId}`);
    lines.push(`---`);

    for (const cmd of processed) {
      lines.push(this.renderCommand(cmd));
    }

    return lines.join('\n') + '\n';
  }

  private renderCommand(cmd: MaestroCommand): string {
    switch (cmd.type) {
      case 'launchApp':
        return '- launchApp';
      case 'tapOn':
        return this.renderSelector('tapOn', cmd.selector);
      case 'doubleTapOn':
        return this.renderSelector('doubleTapOn', cmd.selector);
      case 'longPressOn':
        return this.renderSelector('longPressOn', cmd.selector);
      case 'inputText':
        return `- inputText: "${escape(cmd.text)}"`;
      case 'eraseText':
        return cmd.chars ? `- eraseText: ${cmd.chars}` : '- eraseText';
      case 'swipe':
        if ('direction' in cmd) return `- swipe:\n    direction: ${cmd.direction}`;
        return `- swipe:\n    start: "${cmd.start}"\n    end: "${cmd.end}"`;
      case 'scroll':
        return '- scroll';
      case 'scrollUntilVisible': {
        const dir = 'direction' in cmd && cmd.direction ? `\n    direction: ${cmd.direction.toUpperCase()}` : '';
        return this.renderScrollUntilVisible(cmd.selector, dir);
      }
      case 'assertVisible':
        return this.renderSelector('assertVisible', cmd.selector);
      case 'assertNotVisible':
        return this.renderSelector('assertNotVisible', cmd.selector);
      case 'back':
        return '- back';
      case 'pressKey':
        return `- pressKey: ${cmd.key}`;
      case 'openLink':
        return `- openLink: "${escape(cmd.url)}"`;
      case 'hideKeyboard':
        return '- hideKeyboard';
      case 'waitForAnimationToEnd':
        return '- waitForAnimationToEnd';
      case 'takeScreenshot':
        return '- takeScreenshot';
      default:
        return `# Unknown command: ${(cmd as any).type}`;
    }
  }

  private renderScrollUntilVisible(selector: TapOnSelector, directionLine: string): string {
    switch (selector.kind) {
      case 'text':
        return `- scrollUntilVisible:\n    element: "${escape(selector.text)}"${directionLine}`;
      case 'id':
        return `- scrollUntilVisible:\n    element:\n      id: "${escape(selector.id)}"${directionLine}`;
      case 'contentDescription':
        return `- scrollUntilVisible:\n    element: "${escape(selector.description)}"${directionLine}`;
      default:
        return `- scroll${directionLine ? `\n    direction: ${directionLine.trim().split(': ')[1]}` : ''}`;
    }
  }

  private renderSelector(command: string, selector: TapOnSelector): string {
    switch (selector.kind) {
      case 'text':
        return `- ${command}: "${escape(selector.text)}"`;
      case 'id':
        return `- ${command}:\n    id: "${escape(selector.id)}"`;
      case 'contentDescription':
        return `- ${command}: "${escape(selector.description)}"`;
      case 'relative':
        return `- ${command}:\n    ${selector.relation}: "${escape(selector.anchor)}"`;
      case 'point':
        return `- ${command}:\n    point: "${selector.x}%,${selector.y}%"`;
    }
  }

  private postProcess(commands: MaestroCommand[]): MaestroCommand[] {
    if (commands.length < 2) return commands;

    const result: MaestroCommand[] = [commands[0]];

    for (let i = 1; i < commands.length; i++) {
      const prev = result[result.length - 1];
      const curr = commands[i];

      // Deduplicate consecutive identical taps
      if (prev.type === 'tapOn' && curr.type === 'tapOn' &&
          JSON.stringify(prev.selector) === JSON.stringify(curr.selector)) {
        continue;
      }

      // Group consecutive inputText
      if (prev.type === 'inputText' && curr.type === 'inputText') {
        result[result.length - 1] = { type: 'inputText', text: prev.text + curr.text };
        continue;
      }

      result.push(curr);
    }

    return result;
  }
}

function escape(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
