import { describe, it, expect } from 'vitest';
import { YamlGenerator } from './yaml-generator.js';
import type { MaestroCommand } from '@maestro-recorder/shared';

describe('YamlGenerator', () => {
  const gen = new YamlGenerator();

  describe('generate', () => {
    it('produces valid YAML header', () => {
      const yaml = gen.generate('com.example.app', []);
      expect(yaml).toContain('# Generated by MaestroRecorder');
      expect(yaml).toContain('appId: com.example.app');
      expect(yaml).toContain('---');
    });

    it('renders launchApp', () => {
      const yaml = gen.generate('com.app', [{ type: 'launchApp' }]);
      expect(yaml).toContain('- launchApp');
    });

    it('renders tapOn with text selector', () => {
      const yaml = gen.generate('com.app', [
        { type: 'tapOn', selector: { kind: 'text', text: 'Login' } },
      ]);
      expect(yaml).toContain('- tapOn: "Login"');
    });

    it('renders tapOn with id selector', () => {
      const yaml = gen.generate('com.app', [
        { type: 'tapOn', selector: { kind: 'id', id: 'submit_btn' } },
      ]);
      expect(yaml).toContain('- tapOn:');
      expect(yaml).toContain('    id: "submit_btn"');
    });

    it('renders tapOn with contentDescription', () => {
      const yaml = gen.generate('com.app', [
        { type: 'tapOn', selector: { kind: 'contentDescription', description: 'Navigate up' } },
      ]);
      expect(yaml).toContain('- tapOn: "Navigate up"');
    });

    it('renders tapOn with point selector', () => {
      const yaml = gen.generate('com.app', [
        { type: 'tapOn', selector: { kind: 'point', x: 50, y: 75 } },
      ]);
      expect(yaml).toContain('    point: "50%,75%"');
    });

    it('renders tapOn with relative selector', () => {
      const yaml = gen.generate('com.app', [
        { type: 'tapOn', selector: { kind: 'relative', relation: 'below', anchor: 'Username' } },
      ]);
      expect(yaml).toContain('    below: "Username"');
    });

    it('renders longPressOn', () => {
      const yaml = gen.generate('com.app', [
        { type: 'longPressOn', selector: { kind: 'text', text: 'Delete' } },
      ]);
      expect(yaml).toContain('- longPressOn: "Delete"');
    });

    it('renders doubleTapOn', () => {
      const yaml = gen.generate('com.app', [
        { type: 'doubleTapOn', selector: { kind: 'text', text: 'Zoom' } },
      ]);
      expect(yaml).toContain('- doubleTapOn: "Zoom"');
    });

    it('renders inputText', () => {
      const yaml = gen.generate('com.app', [
        { type: 'inputText', text: 'hello world' },
      ]);
      expect(yaml).toContain('- inputText: "hello world"');
    });

    it('escapes quotes in inputText', () => {
      const yaml = gen.generate('com.app', [
        { type: 'inputText', text: 'say "hi"' },
      ]);
      expect(yaml).toContain('- inputText: "say \\"hi\\""');
    });

    it('renders eraseText with count', () => {
      const yaml = gen.generate('com.app', [
        { type: 'eraseText', chars: 5 },
      ]);
      expect(yaml).toContain('- eraseText: 5');
    });

    it('renders eraseText without count', () => {
      const yaml = gen.generate('com.app', [
        { type: 'eraseText' },
      ]);
      expect(yaml).toContain('- eraseText');
    });

    it('renders swipe with direction', () => {
      const yaml = gen.generate('com.app', [
        { type: 'swipe', direction: 'up' },
      ]);
      expect(yaml).toContain('- swipe:');
      expect(yaml).toContain('    direction: up');
    });

    it('renders swipe with coordinates', () => {
      const yaml = gen.generate('com.app', [
        { type: 'swipe', start: '50%, 75%', end: '50%, 25%' },
      ]);
      expect(yaml).toContain('    start: "50%, 75%"');
      expect(yaml).toContain('    end: "50%, 25%"');
    });

    it('renders scroll', () => {
      const yaml = gen.generate('com.app', [{ type: 'scroll' }]);
      expect(yaml).toContain('- scroll');
    });

    it('renders assertVisible', () => {
      const yaml = gen.generate('com.app', [
        { type: 'assertVisible', selector: { kind: 'text', text: 'Welcome' } },
      ]);
      expect(yaml).toContain('- assertVisible: "Welcome"');
    });

    it('renders back', () => {
      const yaml = gen.generate('com.app', [{ type: 'back' }]);
      expect(yaml).toContain('- back');
    });

    it('renders pressKey', () => {
      const yaml = gen.generate('com.app', [{ type: 'pressKey', key: 'Enter' }]);
      expect(yaml).toContain('- pressKey: Enter');
    });

    it('renders openLink', () => {
      const yaml = gen.generate('com.app', [
        { type: 'openLink', url: 'https://example.com' },
      ]);
      expect(yaml).toContain('- openLink: "https://example.com"');
    });

    it('renders hideKeyboard', () => {
      const yaml = gen.generate('com.app', [{ type: 'hideKeyboard' }]);
      expect(yaml).toContain('- hideKeyboard');
    });

    it('renders waitForAnimationToEnd', () => {
      const yaml = gen.generate('com.app', [{ type: 'waitForAnimationToEnd' }]);
      expect(yaml).toContain('- waitForAnimationToEnd');
    });

    it('renders takeScreenshot', () => {
      const yaml = gen.generate('com.app', [{ type: 'takeScreenshot' }]);
      expect(yaml).toContain('- takeScreenshot');
    });
  });

  describe('postProcess (deduplication)', () => {
    it('deduplicates consecutive identical taps', () => {
      const cmds: MaestroCommand[] = [
        { type: 'tapOn', selector: { kind: 'id', id: 'btn' } },
        { type: 'tapOn', selector: { kind: 'id', id: 'btn' } },
        { type: 'tapOn', selector: { kind: 'id', id: 'btn' } },
      ];
      const yaml = gen.generate('com.app', cmds);
      const matches = yaml.match(/tapOn/g);
      expect(matches).toHaveLength(1);
    });

    it('keeps different consecutive taps', () => {
      const cmds: MaestroCommand[] = [
        { type: 'tapOn', selector: { kind: 'id', id: 'btn1' } },
        { type: 'tapOn', selector: { kind: 'id', id: 'btn2' } },
      ];
      const yaml = gen.generate('com.app', cmds);
      const matches = yaml.match(/tapOn/g);
      expect(matches).toHaveLength(2);
    });

    it('groups consecutive inputText commands', () => {
      const cmds: MaestroCommand[] = [
        { type: 'inputText', text: 'hel' },
        { type: 'inputText', text: 'lo' },
      ];
      const yaml = gen.generate('com.app', cmds);
      expect(yaml).toContain('- inputText: "hello"');
      const matches = yaml.match(/inputText/g);
      expect(matches).toHaveLength(1);
    });
  });

  describe('scrollUntilVisible', () => {
    it('renders with text selector', () => {
      const yaml = gen.generate('com.app', [
        { type: 'scrollUntilVisible', selector: { kind: 'text', text: 'Load More' } },
      ]);
      expect(yaml).toContain('- scrollUntilVisible:');
      expect(yaml).toContain('    element: "Load More"');
    });

    it('renders with id selector', () => {
      const yaml = gen.generate('com.app', [
        { type: 'scrollUntilVisible', selector: { kind: 'id', id: 'footer' } },
      ]);
      expect(yaml).toContain('    element:');
      expect(yaml).toContain('      id: "footer"');
    });

    it('renders with direction', () => {
      const yaml = gen.generate('com.app', [
        { type: 'scrollUntilVisible', selector: { kind: 'text', text: 'End' }, direction: 'DOWN' },
      ]);
      expect(yaml).toContain('    direction: DOWN');
    });
  });
});
