package com.maestrorecorder.cli.generator

import com.maestrorecorder.shared.models.MaestroCommand
import com.maestrorecorder.shared.models.TapOnSelector
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

class YamlGenerator {

    fun generate(appId: String, commands: List<MaestroCommand>): String {
        val sb = StringBuilder()
        val timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))

        sb.appendLine("# Generated by MaestroRecorder")
        sb.appendLine("# Recorded: $timestamp")
        sb.appendLine("appId: $appId")
        sb.appendLine("---")

        val processed = PostProcessor.process(commands)
        for (cmd in processed) {
            sb.appendLine(renderCommand(cmd))
        }

        return sb.toString()
    }

    private fun renderCommand(cmd: MaestroCommand): String = when (cmd) {
        is MaestroCommand.LaunchApp -> "- launchApp"
        is MaestroCommand.TapOn -> renderTapOn(cmd.selector)
        is MaestroCommand.InputText -> "- inputText: \"${escapeYaml(cmd.text)}\""
    }

    private fun renderTapOn(selector: TapOnSelector): String = when (selector) {
        is TapOnSelector.ByText -> "- tapOn: \"${escapeYaml(selector.text)}\""
        is TapOnSelector.ById -> "- tapOn:\n    id: \"${escapeYaml(selector.id)}\""
        is TapOnSelector.ByContentDescription -> "- tapOn: \"${escapeYaml(selector.description)}\""
        is TapOnSelector.ByPoint -> "- tapOn:\n    point: \"${selector.x},${selector.y}\""
    }

    private fun escapeYaml(text: String): String =
        text.replace("\\", "\\\\").replace("\"", "\\\"")
}
