package com.maestrorecorder.cli.generator

import com.maestrorecorder.shared.models.MaestroCommand
import com.maestrorecorder.shared.models.TapOnSelector
import org.junit.jupiter.api.Test
import kotlin.test.assertContains
import kotlin.test.assertTrue

class YamlGeneratorTest {

    private val generator = YamlGenerator()

    @Test
    fun `generates login flow YAML`() {
        val commands = listOf(
            MaestroCommand.LaunchApp,
            MaestroCommand.TapOn(TapOnSelector.ByText("Sign In")),
            MaestroCommand.TapOn(TapOnSelector.ById("email_field")),
            MaestroCommand.InputText("test@example.com"),
            MaestroCommand.TapOn(TapOnSelector.ById("password_field")),
            MaestroCommand.InputText("test123"),
            MaestroCommand.TapOn(TapOnSelector.ByText("Next"))
        )

        val yaml = generator.generate("com.example.app", commands)

        assertContains(yaml, "appId: com.example.app")
        assertContains(yaml, "---")
        assertContains(yaml, "- launchApp")
        assertContains(yaml, "- tapOn: \"Sign In\"")
        assertContains(yaml, "    id: \"email_field\"")
        assertContains(yaml, "- inputText: \"test@example.com\"")
        assertContains(yaml, "    id: \"password_field\"")
        assertContains(yaml, "- inputText: \"test123\"")
        assertContains(yaml, "- tapOn: \"Next\"")
    }

    @Test
    fun `generates coordinate fallback`() {
        val commands = listOf(
            MaestroCommand.TapOn(TapOnSelector.ByPoint(540, 960))
        )

        val yaml = generator.generate("com.example.app", commands)
        assertContains(yaml, "    point: \"540,960\"")
    }

    @Test
    fun `generates content description selector`() {
        val commands = listOf(
            MaestroCommand.TapOn(TapOnSelector.ByContentDescription("Navigate up"))
        )

        val yaml = generator.generate("com.example.app", commands)
        assertContains(yaml, "- tapOn: \"Navigate up\"")
    }

    @Test
    fun `escapes quotes in text`() {
        val commands = listOf(
            MaestroCommand.TapOn(TapOnSelector.ByText("Say \"Hello\""))
        )

        val yaml = generator.generate("com.example.app", commands)
        assertContains(yaml, "- tapOn: \"Say \\\"Hello\\\"\"")
    }

    @Test
    fun `deduplicates consecutive identical taps`() {
        val commands = listOf(
            MaestroCommand.TapOn(TapOnSelector.ByText("OK")),
            MaestroCommand.TapOn(TapOnSelector.ByText("OK")),
            MaestroCommand.TapOn(TapOnSelector.ByText("Cancel"))
        )

        val yaml = generator.generate("com.example.app", commands)
        val okCount = yaml.lines().count { it.contains("- tapOn: \"OK\"") }
        val cancelCount = yaml.lines().count { it.contains("- tapOn: \"Cancel\"") }

        assertTrue(okCount == 1, "Expected 1 'OK' tap but found $okCount")
        assertTrue(cancelCount == 1, "Expected 1 'Cancel' tap but found $cancelCount")
    }

    @Test
    fun `includes header comments`() {
        val yaml = generator.generate("com.example.app", listOf(MaestroCommand.LaunchApp))
        assertContains(yaml, "# Generated by MaestroRecorder")
        assertContains(yaml, "# Recorded:")
    }
}
